print('Write anything here:')
string = input()
print(string[2])
print(string[-1])
print(string[0:5])
print(string[:-2])
print(string[0::2])
print(string[1::2])
print(string[::-1])
print(string[-1::-2])
print(len(string))
